---
title: "R Notebook"
output:
  html_notebook: default
  pdf_document: default
---

```{r}
# Cargar bibliotecas necesarias
require(pacman)
pacman::p_load(dplyr, kableExtra, knitr)
```

```{r}
# Limpiar el entorno y configurar opciones
rm(list = ls())
options(scipen = 999)
```

```{r}
# Cargar datos desde un archivo CSV
datos <- read.csv("ventas_con_nan.csv")
head(datos)
```

```{r}
# Renombrar columnas
names(datos) <- c("fecha", "empleado", "producto", "cantidad", "precio_unitario")
```


```{r}
# Explorar la estructura de los datos
str(datos)
```

```{r}
# Función para crear tabla APA a partir de la salida de str()
crear_tabla_apa <- function(str_output) {
  # Identificar las líneas que contienen información sobre las variables
  lineas_variables <- grep("^\\s*\\$\\s*", str_output, value = TRUE)
  
  # Extraer información de las variables
  nombres <- gsub("^\\s*\\$\\s*([^:]+):.*", "\\1", lineas_variables)
  tipos <- gsub("^.*?:\\s*([^[:space:]]+).*", "\\1", lineas_variables)
  ejemplos <- gsub("^.*?:\\s*(.*)", "\\1", lineas_variables)
  
  # Crear tabla
  tabla <- data.frame(
    Variable = nombres,
    Tipo_de_variable = tipos,
    Ejemplo = ejemplos
  )
  
  return(tabla)
}
```


```{r message=TRUE, warning=TRUE, paged.print=TRUE}
# Generar tabla APA de descripción de variables
str_output <- capture.output(str(datos))
tabla_apa <- crear_tabla_apa(str_output)

# Imprimir tabla con formato APA
kable(tabla_apa, format = "latex", booktabs = TRUE, 
      caption = "Descripción de variables", 
      col.names = names(tabla_apa)) %>%
  kable_styling(latex_options = "hold_position", full_width = FALSE)

```


$$
3x+3=0
$$
